# Generated by Django 2.0.3 on 2018-03-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0004_persontotitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontotitle',
            name='Completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completion Date'),
        ),
    ]
