# Generated by Django 2.0.3 on 2018-03-12 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0005_persontotitle_completion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persontotitle',
            name='Completion_date',
        ),
    ]
